variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALPINE_VERSION: "3.13"
  SBCL_VERSION: 2.1.1
  DOCKER_HUB_CI_REPO: daewok/clpm-ci

image: clfoundation/sbcl:$SBCL_VERSION-alpine$ALPINE_VERSION

stages:
  - prep
  - build

##############################################################################
# Build static releases
##############################################################################

.static-release:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  script:
    - sbcl --script scripts/build-static-release.lisp
  artifacts:
    paths:
      - releases/

static-release:linux:amd64:
  extends: .static-release
  variables:
    ARCH: amd64

##############################################################################
# Build dynamic executables
##############################################################################

.dynamic-exec:
  stage: build
  image: clfoundation/sbcl:$SBCL_VERSION
  script:
    - cd /usr/local/src/sbcl
    - sh make.sh --with-sb-linkable-runtime
    - sh install.sh
    - cd $CI_PROJECT_DIR
    - sbcl --script scripts/build.lisp
  artifacts:
    paths:
      - build/bin/

dynamic-exec:linux:amd64:
  extends: .dynamic-exec
  needs: []
