variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALPINE_VERSION: "3.13"
  SBCL_VERSION: 2.1.1
  DOCKER_HUB_CI_REPO: daewok/clpm-ci

image: clfoundation/sbcl:$SBCL_VERSION-alpine$ALPINE_VERSION

stages:
  - prep
  - build

##############################################################################
# Build CI Images
##############################################################################

# Build the image used for making the executable.
ci-image:amd64:
  stage: prep
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_HUB_USERNAME\",\"password\":\"$DOCKER_HUB_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache --cache-repo $DOCKER_HUB_CI_REPO --context $CI_PROJECT_DIR --build-arg sbcl_version=$SBCL_VERSION --build-arg alpine_version=$ALPINE_VERSION --dockerfile $CI_PROJECT_DIR/docker/Dockerfile.linux-static-builder --destination $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-amd64

##############################################################################
# Build static releases
##############################################################################

.static-release:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  script:
    - sbcl --script scripts/build-static-release.lisp
  artifacts:
    paths:
      - releases/

static-release:linux:amd64:
  extends: .static-release
  variables:
    ARCH: amd64
  needs:
    - ci-image:amd64

##############################################################################
# Build dynamic executables
##############################################################################

.dynamic-exec:
  stage: build
  image: clfoundation/sbcl:$SBCL_VERSION
  script:
    - cd /usr/local/src/sbcl
    - sh make.sh --with-sb-linkable-runtime
    - sh install.sh
    - cd $CI_PROJECT_DIR
    - sbcl --script scripts/build.lisp
  artifacts:
    paths:
      - build/bin/

dynamic-exec:linux:amd64:
  extends: .dynamic-exec
  needs: []
