variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALPINE_VERSION: "3.13"
  DEBIAN_VERSION: stretch
  SBCL_VERSION: 2.1.1
  DOCKER_HUB_CI_REPO: daewok/clpm-ci

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - prep
  - build

##############################################################################
# Build static releases
##############################################################################

.static-release:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  before_script:
    - git checkout -B $CI_COMMIT_BRANCH $CI_COMMIT_SHA
  script:
    - sbcl --script scripts/build-release.lisp --static
  artifacts:
    paths:
      - releases/
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH'

static-release:linux:amd64:
  extends: .static-release
  variables:
    ARCH: amd64

static-release:linux:arm64:
  extends: .static-release
  variables:
    ARCH: arm64
  tags:
    - arm64v8

##############################################################################
# Build dynamic releases
##############################################################################

.dynamic-release:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-$DEBIAN_VERSION-$ARCH
  before_script:
    - git checkout -B $CI_COMMIT_BRANCH $CI_COMMIT_SHA
  script:
    - sbcl --script scripts/build-release.lisp
  artifacts:
    paths:
      - releases/
  rules:
    - if: '$CI_COMMIT_BRANCH'

dynamic-release:linux:amd64:
  extends: .dynamic-release
  variables:
    ARCH: amd64

# dynamic-release:linux:arm64:
#   extends: .dynamic-release
#   variables:
#     ARCH: arm64
#   tags:
#     - arm64v8

# dynamic-release:linux:armv7:
#   extends: .dynamic-release
#   variables:
#     ARCH: armhf
#   tags:
#     - armv7

dynamic-release:macos:amd64:
  stage: build
  extends: .dynamic-release
  tags:
    - macos-0.4-amd64

dynamic-release:windows:amd64:
  extends: .dynamic-release
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-windowsservercore
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: none
    GIT_CHECKOUT: "false"
  before_script:
    - git checkout -B $CI_COMMIT_BRANCH $CI_COMMIT_SHA
    - git submodule init
    - git submodule update
  script:
    - $env:WIX = "C:\wix"
    - sbcl --script scripts/build-release.lisp
    - sbcl --script scripts/build-msi.lisp
  tags:
    - windows-amd64
