variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALPINE_VERSION: "3.13"
  SBCL_VERSION: 2.1.1
  DOCKER_HUB_CI_REPO: daewok/clpm-ci

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - prep
  - build

##############################################################################
# Build static releases
##############################################################################

.static-release:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  before_script:
    - git checkout -B $CI_COMMIT_BRANCH $CI_COMMIT_SHA
  script:
    - sbcl --script scripts/build-static-release.lisp
  artifacts:
    paths:
      - releases/
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH'

static-release:linux:amd64:
  extends: .static-release
  variables:
    ARCH: amd64

static-release:linux:arm64:
  extends: .static-release
  variables:
    ARCH: arm64
  tags:
    - arm64v8

##############################################################################
# Build dynamic executables
##############################################################################

.dynamic-exec:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  before_script:
    - git checkout -B $CI_COMMIT_BRANCH $CI_COMMIT_SHA
  script:
    - sbcl --script scripts/build.lisp
  artifacts:
    paths:
      - build/bin/
  rules:
    - if: '$CI_COMMIT_BRANCH'

dynamic-exec:linux:amd64:
  extends: .dynamic-exec
  variables:
    ARCH: amd64

dynamic-exec:linux:arm64:
  extends: .dynamic-exec
  variables:
    ARCH: arm64
  tags:
    - arm64v8

# dynamic-exec:linux:armv7:
#   extends: .dynamic-exec
#   variables:
#     ARCH: armhf
#   tags:
#     - armv7

dynamic-exec:macos:amd64:
  stage: build
  extends: .dynamic-exec
  tags:
    - macos-0.4-amd64

dynamic-exec:windows:amd64:
  extends: .dynamic-exec
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-windowsservercore
