variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALPINE_VERSION: "3.13"
  SBCL_VERSION: 2.1.1
  DOCKER_HUB_CI_REPO: daewok/clpm-ci

image: clfoundation/sbcl:$SBCL_VERSION-alpine$ALPINE_VERSION

stages:
  - prep
  - build

##############################################################################
# Build static releases
##############################################################################

.static-release:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  script:
    - sbcl --script scripts/build-static-release.lisp
  artifacts:
    paths:
      - releases/
  needs: []

static-release:linux:amd64:
  extends: .static-release
  variables:
    ARCH: amd64

static-release:linux:arm64:
  extends: .static-release
  variables:
    ARCH: arm64
  tags:
    - arm64v8

##############################################################################
# Build dynamic executables
##############################################################################

.dynamic-exec:
  stage: build
  image: $DOCKER_HUB_CI_REPO:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  script:
    - sbcl --script scripts/build.lisp
  artifacts:
    paths:
      - build/bin/

dynamic-exec:linux:amd64:
  extends: .dynamic-exec
  variables:
    ARCH: amd64

dynamic-exec:linux:arm64:
  extends: .dynamic-exec
  variables:
    ARCH: arm64
  tags:
    - arm64v8
