#+TITLE: Developer README

This file is meant to be a colleciton of notes for CLPM developers that users
don't typically have to worry about.

* CI

  The CI jobs require SBCL to be built with non standard options (and a
  patch). To avoid having to build SBCL with these changes in every job, we
  build a Docker image with this patched SBCL. The ideal situation would be to
  have a job early in the pipeline that builds the image (only if needed) and
  then the later jobs consume this image.

  Unfortunately, gitlab.common-lisp.net does not have the built in container
  registry enabled. This means that we have to use a third party, such as
  Docker Hub, to hold the image between jobs. I strongly prefer to not put
  access tokens to my personal Docker Hub account on the clpm group (as I'd
  like to eventually have more people added to the group). Therefore, I
  (etimmons) build the CI images locally, push them to Docker Hub, and then
  just use those images in the CI pipeline. In the future we may want to make a
  clpm org on Docker Hub or see if the admins can enable the built-in Docker
  registry for us.

  Build on amd64:
  #+begin_src shell
    ARCH=amd64
    SBCL_VERSION=2.1.1
    ALPINE_VERSION=3.13
    docker build --build-arg sbcl_version=$SBCL_VERSION \
                 --build-arg alpine_version=$ALPINE_VERSION \
                 -t daewok/clpm-ci:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH \
                 --pull \
                 --platform=linux/amd64 \
                 -f docker/Dockerfile.linux-ci \
                 docker
    docker push daewok/clpm-ci:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  #+end_src

  Build on armhf:
  #+begin_src shell
    ARCH=armhf
    SBCL_VERSION=2.1.1
    ALPINE_VERSION=3.13
    docker build --build-arg sbcl_version=$SBCL_VERSION \
                 --build-arg alpine_version=$ALPINE_VERSION \
                 -t daewok/clpm-ci:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH \
                 --pull \
                 --platform=linux/arm/v7 \
                 -f docker/Dockerfile.linux-ci \
                 docker
    docker push daewok/clpm-ci:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  #+end_src

  Build on arm64:
  #+begin_src shell
    ARCH=arm64
    SBCL_VERSION=2.1.1
    ALPINE_VERSION=3.13
    docker build --build-arg sbcl_version=$SBCL_VERSION \
                 --build-arg alpine_version=$ALPINE_VERSION \
                 -t daewok/clpm-ci:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH \
                 --pull \
                 --platform=linux/arm64/v8 \
                 -f docker/Dockerfile.linux-ci \
                 docker
    docker push daewok/clpm-ci:$SBCL_VERSION-alpine$ALPINE_VERSION-$ARCH
  #+end_src

* Dependencies

  CLPM has a lot of dependencies. Probably too many, but that's a problem for
  another day. CLPM has a habit of finding issues in its dependencies that
  sometimes take a while to get fixed. To support both getting the needed fixes
  before upstream merges them and to make builds reproducible, we use git
  submodules for all our dpeendencies.

  One day, I'd like to see CLPM self host itself so we can have a clpmfile.lock
  instead. But CLPM needs to get a little more stable first.

** Fixes

   This is a list of the fixes we have submitted upstream and their current
   status. For most of these, if there is an outstanding PR, CLPM pulls its
   code from a fork that has the PR merged. We don't necessarily depend on all
   these libraries any more, but PRs are kept for posterity.

   - cl-plus-ssl ::
     - [ ] https://github.com/cl-plus-ssl/cl-plus-ssl/pull/116
     - [ ] https://github.com/cl-plus-ssl/cl-plus-ssl/pull/115 (not submitted
       by us, but needed by us)
   - osicat ::
     - [ ] https://github.com/osicat/osicat/pull/39
   - dexador ::
     - [ ] https://github.com/fukamachi/dexador/pull/86
     - [ ] https://github.com/fukamachi/dexador/issues/87
   - cffi ::
     - [ ] https://github.com/cffi/cffi/pull/141
   - zippy ::
     - [X] https://github.com/Shinmera/zippy/pull/1
   - cl-unicode ::
     - [X] https://github.com/edicl/cl-unicode/pull/26
   - archive :: There doesn't seem to be any active upstream for this
     project... May try sending some merge requests to sharplispers, but if
     that fails, CLPM may have to hard fork/try to assume ownership.
   - cl-semver ::
     - [X] https://github.com/cldm/cl-semver/pull/4
     - [X] https://github.com/cldm/cl-semver/pull/5
   - deploy ::
     - [X] https://github.com/Shinmera/deploy/pull/12
     - [X] https://github.com/Shinmera/deploy/pull/13
   - mito ::
     - [X] https://github.com/fukamachi/mito/pull/53
