#+TITLE: CLPM Configuration
#+AUTHOR: CLPM Developers
#+EMAIL: clpm-devel@common-lisp.net

CLPM is configured using a file named =clpm.conf=. CLPM constructs a list of
directories to search for this file and the first instance found wins. The
default order of directories searched is first the =common-lisp/clpm= folder of
the user's XDG config directory (typically =$HOME/.confg/=), then in the system
config folder (typically =/etc/=). The order can be changed with the
=CLPM_CONFIG_DIRS= environment variable. If specified, it must be a list of
directories separated by your OS's conventional directory separator. If any
entry in the list is empty. The default search locations will be spliced into
the list.

The contents of =clpm.conf= must be a single list that starts with ~clpm-config~
and the rest must be a plist. Each key in the plist names either a value or a
section. If it names a section, the value must be another plist. If it names a
value, the value is read according to the rules for that value.

The following describe the configuration options for clpm.

* ~:archives~

  + ~:tar-method~ :: A keyword specifying which tar implementation to
    use. Defaults to =:auto=.

** ~:tar~

   Settings for the tar method that uses an external tar program.

   + ~:path~ :: Path to the =tar= executable. Defaults to ="tar"=.

* ~:bundle~
** ~:local~
*** ~"PROJECT-NAME"~
    When using the bundle commands, instead of using the upstream git repository
    for PROJECT-NAME, use a local checkout instead.

    + ~:path~ :: Path to the folder containing the checkout of the git
      repository to use.

* ~:git~
** ~:remotes~
*** ~"HOSTNAME"~
    Provide configuration for interacting with HOSTNAME to fetch git repos.

    + ~:username~ :: A string containing the username to use when connecting to
      the server.
    + ~:password~ :: A string containing the password to use when connecting to
      the server.
    + ~:method~ :: A keyword describing how to connect to the server. Can be one
      of:
      + ~:https~ :: Connect using HTTPS.
      + ~:http~ :: Connect using HTTP.
      + ~:ssh~ :: Connect using SSH.
    + ~:port~ :: Port to connect on.
* ~:http~
** ~:headers~
*** ~"HOSTNAME~
**** ~"HEADER-NAME"~
     When performing a non-git HTTP request to HOSTNAME, provide a header with
     the name HEADER-NAME.

     + ~:secure-only-p~ :: If non-NIL, send this header only on secure
       connections.
     + ~:value~ :: The value to send for the header. If a string, the contents
       of the string are used literally. If a pathname naming an executable
       file, that file is executed and whatever it prints to its standard output
       is used as the value. If a pathname naming a non-executable file, the
       contents of the file are sent.

* ~:http-client~
  + ~:method~ :: The default method to use to as an HTTP client. Defaults to
    =:auto=.

** ~:curl~
   Settings for the curl method that uses an external curl program.

   + ~:path~ :: Path to the =curl= executable. Defaults to ="curl"=.

* ~:grovel~
** ~:sandbox~
   Options for configuring the sandbox used to isolate processes that grovel for
   dependencies from .asd files.

   + ~:method~ :: The default method to use as the sandbox. Defaults to =:auto=.

* ~:sources~
** ~"SOURCE-NAME~
   Options to configure the source with the name SOURCE-NAME. See [[file:sources.org][sources.org]]
   for more information on the available sources and their configuration
   options.

   Must contain a value for ~:type~ that names the type of source this is.
