#+TITLE: CLPM Configuration
#+AUTHOR: CLPM Developers
#+EMAIL: clpm-devel@common-lisp.net

CLPM is configured using a file named =clpm.conf=. CLPM constructs a list of
directories to search for this file and the first instance found wins. The
default order of directories searched is first the =common-lisp/clpm= folder of
the user's XDG config directory (typically =$HOME/.confg/=), then in the system
config folder (typically =/etc/=). The order can be changed with the
=CLPM_CONFIG_DIRS= environment variable. If specified, it must be a list of
directories separated by your OS's conventional directory separator. If any
entry in the list is empty. The default search locations will be spliced into
the list.

Logically, CLPM is configured by a series of nested tables. The config file
describes these tables using a series of forms. It is recommended (and will
likely be required in the future) that the first form in the config file
declares the version of the config file API being used, such as the
following. The described version API is 0.1.

#+begin_src common-lisp
  (version "0.1")
#+end_src

Each subsequent form must describe a table. Each subsequent form must start
with ~table~ or ~(table &rest path)~. The body of the form then contains a
plist describing key/value pairs for that table. Tables can be nested by either
declaring toplevel tables with overlapping paths or by embedding a table
(without a path) as a value inside another table.

For example, the following config would force CLPM to use curl as its HTTP
client and use the primary quicklisp destribution as a source.

#+begin_src common-lisp
  (version "0.1")

  ((table :http-client)
   :method :curl)

  ((table :sources "quicklisp")
   :type :quicklisp
   :url "https://beta.quicklisp.org/dist/quicklisp.txt")
#+end_src

The following describes the available configuration tables for CLPM. Each
header describes a table (or sub table). The lists in each section describe
that tables keys.

* ~:archives~

  + ~:tar-method~ :: A keyword specifying which tar implementation to
    use. Defaults to =:auto=.

** ~:tar~

   Settings for the tar method that uses an external tar program.

   + ~:path~ :: Path to the =tar= executable. Defaults to ="tar"=.

* ~:bundle~
** ~:local~
*** ~"PROJECT-NAME"~
    When using the bundle commands, instead of using the upstream git repository
    for PROJECT-NAME, use a local checkout instead.

    + ~:path~ :: Path to the folder containing the checkout of the git
      repository to use.

* ~:git~
** ~:remotes~
*** ~"HOSTNAME"~
    Provide configuration for interacting with HOSTNAME to fetch git repos.

    + ~:username~ :: A string containing the username to use when connecting to
      the server.
    + ~:password~ :: A string containing the password to use when connecting to
      the server.
    + ~:method~ :: A keyword describing how to connect to the server. Can be one
      of:
      + ~:https~ :: Connect using HTTPS.
      + ~:http~ :: Connect using HTTP.
      + ~:ssh~ :: Connect using SSH.
    + ~:port~ :: Port to connect on.
* ~:http~
** ~:headers~
*** ~"HOSTNAME~
**** ~"HEADER-NAME"~
     When performing a non-git HTTP request to HOSTNAME, provide a header with
     the name HEADER-NAME.

     + ~:secure-only-p~ :: If non-NIL, send this header only on secure
       connections.
     + ~:value~ :: The value to send for the header. Must be a string.
     + ~:exec~ :: A path to a file that, when executed, prints the header value
       to its standard output. Must be a string or pathname.
     + ~:contents~ :: A path to a file that contains the value to use for the
       header. Must be a string or pathname.

* ~:http-client~
  + ~:method~ :: The default method to use to as an HTTP client. Defaults to
    =:auto=.

** ~:curl~
   Settings for the curl method that uses an external curl program.

   + ~:path~ :: Path to the =curl= executable. Defaults to ="curl"=.

* ~:grovel~
** ~:sandbox~
   Options for configuring the sandbox used to isolate processes that grovel for
   dependencies from .asd files.

   + ~:method~ :: The default method to use as the sandbox. Defaults to =:auto=.

* ~:sources~
** ~"SOURCE-NAME~
   Options to configure the source with the name SOURCE-NAME. See [[file:sources.org][sources.org]]
   for more information on the available sources and their configuration
   options.

   Must contain a value for ~:type~ that names the type of source this is.
