#+TITLE: CLPM Sources
#+AUTHOR: CLPM Developers
#+EMAIL: clpm-devel@common-lisp.net

A repository of Common Lisp projects is called a "source". The source you are
most likely familiar with is Quicklisp, but CLPM is designed to be extended to
support multiple sources and source types. This will allow you to easily use
CLPM for things such as internal projects that can't be released to public
repositories.

The type of every source must be specified with a keyword.

* Quicklisp

  A Quicklisp style source contains a subscription metadata file (such as the
  primary Quicklisp one located at
  https://beta.quicklisp.org/dist/quicklisp.txt). Additionally, there must a
  file whose name is the same but suffixed with "-versions" (e.g.,
  https://beta.quicklisp.org/dist/quicklisp-versions.txt) that points to the
  dist file for every version of the distribution.

  The type designator for a Quicklisp like source is =:quicklisp=. A quicklisp
  distribution can be configured with the following options:

  + =url= :: The URL to the subscription metadata file.
  + =force-https= :: If true, the protocol for all URLs is changed to https
    before downloading any files. This is useful because all URLs contained in
    the primary Quicklisp distribution have http as the protocol even though
    they are also served over https. If the =url= uses the =https= scheme,
    =force-https= is implicitly set to true and cannot be disabled.

  The following table can be added to your CLPM config file to use the primary
  Quicklisp distribution.

  #+begin_src common-lisp
    (clpm-config
     :sources
     ("quicklisp"
      (:type :quicklisp
       :url "https://beta.quicklisp.org/dist/quicklisp.txt"
       :force-https t)))
  #+end_src
