#+TITLE: CLPM Storage
#+AUTHOR: CLPM Developers
#+EMAIL: clpm-devel@common-lisp.net
#+OPTIONS: toc:1 num:nil

This document specifies what files on your computer CLPM will touch and why.

* Cache

  CLPM stores its cache in the =clpm= subfolder of your user XDG[fn:1] cache
  directory (typically =~/.cache/=). The location can be overridden using the
  =CLPM_CACHE_DIR= environment variable.

  In the cache folder, CLPM stores tarballs from sources, git repos, fasls from
  bundles with output translations enabled, metadata gathered from package
  sources, etc.

  Generally, that cache can be deleted at any time (except when an instance of
  CLPM is running), and CLPM can redownload or generate files as necessary.

* Data

  CLPM installs systems to the =clpm= subfolder of your user XDG data directory
  (typically =~/.local/share/=). The location can be overridden using the
  =CLPM_DATA_DIR= environment variable.

* Footnotes

[fn:1] https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
